### ISSUE TITLE
index files for tagged.bam

### ISSUE THREAD

**Issue by ildargv** [Magdoll/AAV#4]
Hi Liz,

Thank you for the great work. The python code works smoothly, except for the messages displayed at the end of it running (see below). The output is there and usable. Is that something one should ignore? Thanks!

python3 ./summarize_AAV_alignment.py --cpus 8 data.ref.hifi.SortedByName.sam data.ref.hifi
Total 302835 reads, dividing into 8 chunks of size 37855...
Going from 0 to 37855
Going from 37855 to 75710
Going from 75710 to 113565
Going from 113565 to 151420
Going from 151420 to 189275
Going from 189275 to 227130
Going from 227130 to 264985
Going from 264985 to 302840
[E::idx_find_and_load] Could not retrieve index file for 'data.ref.hifi.1.tagged.bam'
[E::idx_find_and_load] Could not retrieve index file for 'data.ref.hifi.2.tagged.bam'
[E::idx_find_and_load] Could not retrieve index file for 'data.ref.hifi.3.tagged.bam'
[E::idx_find_and_load] Could not retrieve index file for 'data.ref.hifi.4.tagged.bam'
[E::idx_find_and_load] Could not retrieve index file for 'data.ref.hifi.5.tagged.bam'
[E::idx_find_and_load] Could not retrieve index file for 'data.ref.hifi.6.tagged.bam'
[E::idx_find_and_load] Could not retrieve index file for 'data.ref.hifi.7.tagged.bam'
[E::idx_find_and_load] Could not retrieve index file for 'data.ref.hifi.8.tagged.bam'

**Comment by Magdoll** [comment]
Hi @ildargv  it's a warning you can safely ignore! the index files are NOT needed at all.
