### ISSUE TITLE
Vector Sequence Question

### ISSUE THREAD

**Issue by bcantarel** [Magdoll/AAV#6]
I had one quick question on the tutorial.  Is the vector sequence for scAAV -- the sequence + revcomp? or just the sequence?
Thanks!

**Comment by Magdoll** [comment]
Hi @bcantarel  - when providing the vector "genome" for scAAV you should provide just the ITR to ITR - in one pass, not revcomp. The script uses the fact that a scAAV PacBio read will wrap around the ITR twice to characterize it properly as scAAV, otherwise it'll be considered ssAAV.
